services:

  neo4j:
    container_name: neo4j
    image: neo4j:5.26.0
    restart: always
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-pa55w0rd}
    ports:
      - "${NEO4J_HTTP_PORT:-7474}:7474"   # HTTP Browser UI
      - "${NEO4J_BOLT_PORT:-7687}:7687"   # Bolt 协议（SDK 连接）
    volumes:
      - ./volumes/neo4j/logs:/logs
      - ./volumes/neo4j/config:/config
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/plugins:/plugins
    networks:
      - devopsnetwork
