services:

  neo4j:
    container_name: neo4j
    image: neo4j:5.26.0
    restart: always
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"   # HTTP Browser UI
      - "7687:7687"   # Bolt 协议（SDK 连接）
    volumes:
      - ./volumes/neo4j/logs:/logs
      - ./volumes/neo4j/config:/config
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/plugins:/plugins
    networks:
      - devopsnetwork

networks:
  devopsnetwork:
    driver: bridge
