services:
  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    command: >
      sh -c 'if [ -n "$$REDIS_PASSWORD" ]; then
      redis-server --requirepass "$$REDIS_PASSWORD";
      else
      redis-server;
      fi'
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./volumes/redis/data:/data
    networks:
      - devopsnetwork
